server:
  port: 8877

knife4j:
  enable: true

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: ENC(eKCHg5ydOAmcTctLzVwDKRxeVqF5nxDgXDH3xRCAHtZXAfvMtgNJi82sZIUKNvHquMxxqjVnWwEj6l2Xao8Mk2sPGObqtKmjV+UbWEZ7jUHOhG8EpP6gTAjdpI9gMVFU4ec1nvo5Rkw=)
    username: ENC(budJdplvV7XO+N4Uv0Z2Gw==)
    password: ENC(xB+0+iJMhrC1zYAuZr46wrC+Pz7Oc4kz)
    driver-class-name: com.mysql.cj.jdbc.Driver